version: "3.8"

services:
  household-gollum:
    image: gollumwiki/gollum:${GOLLUM_VERSION}
    volumes:
      - ./wiki:/wiki
    expose:
      - "4567"
    command: ["--port", "4567", "--host", "0.0.0.0"]

  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      WIKI_USER: ${WIKI_USER}
      WIKI_PASS_HASH: ${WIKI_PASS_HASH}